// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import ...

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsoRTCB4AFOjXnVDwMcl8Hd9LRBypApzw',
    appId: '1:282965618156:web:2dadb90c8c23f856aaa4c9',
    messagingSenderId: '282965618156',
    projectId: 'final-project-29b88',
    authDomain: 'final-project-29b88.firebaseapp.com',
    storageBucket: 'final-project-29b88.appspot.com',
    measurementId: 'G-C8F7DJYZE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD56eAJYmV5dFd5EVZdAa_aGPuTaoiXodg',
    appId: '1:282965618156:android:20b107271f6a8710aaa4c9',
    messagingSenderId: '282965618156',
    projectId: 'final-project-29b88',
    storageBucket: 'final-project-29b88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO2N12PLe7zFE222P2VwYDvccno_z4XPs',
    appId: '1:282965618156:ios:dc834c0ee60a1573aaa4c9',
    messagingSenderId: '282965618156',
    projectId: 'final-project-29b88',
    storageBucket: 'final-project-29b88.appspot.com',
    iosBundleId: 'com.example.finalproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO2N12PLe7zFE222P2VwYDvccno_z4XPs',
    appId: '1:282965618156:ios:f2cf4f713c78161baaa4c9',
    messagingSenderId: '282965618156',
    projectId: 'final-project-29b88',
    storageBucket: 'final-project-29b88.appspot.com',
    iosBundleId: 'com.example.finalproject.RunnerTests',
  );
}
